<a href="https://colab.research.google.com/github/owaisali246/pytorch/blob/main/Pytorch_code_camp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

YT-time: 1:22:00

In [69]:
# imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from torch import float32, float16, float64, int8

In [ ]:
print(torch.__version__)
!nvidia-smi

# Introduction to Tensors

## Scalars

In [3]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


## Vectors

In [6]:
vector = torch.tensor([7, 8])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 8])
1
torch.Size([2])


## Matrix

In [9]:
MATRIX = torch.tensor([[7, 8], [1, 9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0][1])

tensor([[7, 8],
        [1, 9]])
2
torch.Size([2, 2])
tensor(8)


## Tensors

In [ ]:
TENSOR = torch.tensor([[[7, 5], [1, 9], [2, 2]], [[1, 4], [2, 8], [3, 7]]])
print(TENSOR)

print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1])

### Random tensors
Random tensors are important b/c the way neural networks work is that they start from random tensors and then update themselves in order to better represent the data `random tensors -> look at data -> update tensors -> repeat`

In [ ]:
# How to generate a random tensor of size
TENSOR = torch.rand(5, 5, 15)
print(TENSOR)

In [35]:
# generate a tensor for an image
image = torch.rand(500, 500, 3) # height, width, rgb color channels
print(image.shape, image.ndim)

torch.Size([500, 500, 3]) 3


In [ ]:
# zeros or ones tensors
zeros = torch.zeros(5, 5)
print(zeros)

ones = torch.ones(5, 5)
print(ones)

In [ ]:
# generate tensors of varying range
tens = torch.arange(start=0, end=100, step=5)
print(tens)
zeros_like = torch.zeros_like(tens)
print(zeros_like)

In [ ]:
# Tensor datatypes

tens = torch.rand(2,2, 2).detach().clone()
tens = tens.to(dtype=None, device=None)
tens.requires_grad_(False)
# tyoes like float16, float32, etc,. If you give None it will fallback to default float32
# device refers to 'cpu' or 'cuda'
# track gradient of the tensors as it goes through different operations


print(tens.dtype)
print(tens.type(float16))
print(tens.type(float64))
print(tens.type(int8))
print(tens.type(float16) + tens.type(float16), '\n')

print("Tensor shape:",tens.shape)
print("Tensor is on device:",tens.device)

In [ ]:
# Basic Tensor Operations

# Create two tensors
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

# Addition
addition_result = tensor_a + tensor_b
print("Addition:", addition_result)

# Subtraction
subtraction_result = tensor_b - tensor_a
print("Subtraction:", subtraction_result)

# Multiplication (element-wise)
multiplication_result = tensor_a * tensor_b
print("Element-wise Multiplication:", multiplication_result)

# Division (element-wise)
division_result = tensor_b / tensor_a
print("Element-wise Division:", division_result)

# Matrix Multiplication (dot product)
# For matrix multiplication, the inner dimensions must match.
# Let's create slightly different tensors for this example.
tensor_c = torch.tensor([[1, 2], [3, 4]])
tensor_d = torch.tensor([[5, 6], [7, 8]])

matrix_multiplication_result = torch.matmul(tensor_c, tensor_d)
print("Matrix Multiplication:", matrix_multiplication_result)

# Another way to do matrix multiplication
matrix_multiplication_result_alt = tensor_c @ tensor_d
print("Matrix Multiplication (using @):", matrix_multiplication_result_alt)

In [ ]:
tensor_e = torch.randint(0, 10, (2, 3, 3), dtype=int8)
print(tensor_e)
print(tensor_e.dtype)
print(tensor_e * 10)
print(tensor_e + 10)
print(tensor_e - 10)
print(tensor_e / 10)

In [116]:
tensor_a = torch.randint(0, 10, (1000,), dtype=int8)
tensor_b = torch.randint(0, 10, (1000,), dtype=int8)

In [125]:
%%time
value = 0
for i in range(len(tensor_a)):
    value += tensor_a[i] + tensor_b[i]
print(value)

tensor(114, dtype=torch.int8)
CPU times: user 7.11 ms, sys: 1.01 ms, total: 8.12 ms
Wall time: 8.2 ms


In [133]:
%%time
tens_a = torch.add(tensor_a, tensor_b)

CPU times: user 772 µs, sys: 31 µs, total: 803 µs
Wall time: 621 µs


In [137]:
%%time
tens = tensor_a + tensor_b

CPU times: user 146 µs, sys: 6 µs, total: 152 µs
Wall time: 157 µs


In [146]:
# Transponse a Tensor

tensor_a = torch.randint(0, 50, (2, 5), dtype=int8)
print(tensor_a)
print(tensor_a.T)

tensor([[39, 29, 49, 19,  2],
        [38, 27, 23, 47, 49]], dtype=torch.int8)
tensor([[39, 38],
        [29, 27],
        [49, 23],
        [19, 47],
        [ 2, 49]], dtype=torch.int8)


In [147]:
# Tensor Aggregation

# Create a tensor
tensor_agg = torch.randint(0, 100, (5, 5), dtype=torch.int8)
print("Original Tensor:")
print(tensor_agg)

# Find the minimum value
min_value = torch.min(tensor_agg)
print("\nMinimum value:", min_value, tensor_agg.min())

# Find the maximum value
max_value = torch.max(tensor_agg)
print("Maximum value:", max_value, tensor_agg.max())

# Find the mean value
mean_value = torch.mean(tensor_agg)
print("Mean value:", mean_value, tensor_agg.mean())

# Find the sum of all elements
sum_value = torch.sum(tensor_agg)
print("Sum of all elements:", sum_value, tensor_agg.sum())

# Find the index of the minimum value
argmin_value = torch.argmin(tensor_agg)
print("Index of minimum value (flattened):", argmin_value, tensor_agg.argmin())

# Find the index of the maximum value
argmax_value = torch.argmax(tensor_agg)
print("Index of maximum value (flattened):", argmax_value, tensor_agg.argmax())

# Aggregation along a specific dimension (e.g., across columns, dim=1)
mean_across_columns = torch.mean(tensor_agg, dim=1)
print("\nMean across columns:", mean_across_columns, tensor_agg.mean(dim=1))

# Aggregation along a specific dimension (e.g., across rows, dim=0)
sum_across_rows = torch.sum(tensor_agg, dim=0)
print("Sum across rows:", sum_across_rows, tensor_agg.sum(dim=0))

Original Tensor:
tensor([[75., 13., 89., 51., 24.],
        [45., 99., 42., 54., 90.],
        [68., 93.,  6., 56., 85.],
        [51., 20., 62., 62., 13.],
        [68., 54., 14., 86., 29.]])

Minimum value: tensor(6.) tensor(6.)
Maximum value: tensor(99.) tensor(99.)
Mean value: tensor(53.9600) tensor(53.9600)
Sum of all elements: tensor(1349.) tensor(1349.)
Index of minimum value (flattened): tensor(12) tensor(12)
Index of maximum value (flattened): tensor(6) tensor(6)

Mean across columns: tensor([50.4000, 66.0000, 61.6000, 41.6000, 50.2000]) tensor([50.4000, 66.0000, 61.6000, 41.6000, 50.2000])
Sum across rows: tensor([307., 279., 213., 309., 241.]) tensor([307., 279., 213., 309., 241.])
